config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :surfboards do
    resources :bookings, only: [:create, :new]
    resources :reviews, only: [:create]
    resource :favorites, only: [:create]
  end

  resources :bookings, only: [:index, :show, :destroy] do
    member do
      put :accept # This adds a PUT route for the accept action
    end
  end

  resources :favorites, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :surfboard
  enum status: { requested: "requested", confirmed: "confirmed" }


  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :status, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :surfboard
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :surfboard_id # needs to examine

  belongs_to :surfboard

  validates :comment, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/surfboard.rb
class Surfboard < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :size, presence: true
  validates :color, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :surfboards
  has_many :bookings
  has_many :favorites, dependent: :destroy
  has_many :favorite_surfboards, through: :favorites, source: :surfboard
  has_many :booking_requests, -> { where(status: :requested) }, class_name: 'Booking'


  validates :user_name, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @surfboards = Surfboard.where(user_id: current_user.id)
    @bookings = current_user.bookings
    @booking_requests = Booking.where(surfboard: @surfboards, status: 'requested')
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @surfboard = Surfboard.find(params[:surfboard_id])
    @booking.user = current_user
    @booking.surfboard = @surfboard
    @booking.status = "requested"
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @booking = Booking.new
    @surfboard = Surfboard.find(params[:surfboard_id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  def accept
    @booking_request = Booking.find(params[:id]) # Find the booking by its ID
    @booking_request.update(status: 'confirmed')
    redirect_to bookings_path, notice: "Booking request accepted successfully!"
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :surfboard_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def index
    @favorites = current_user.favorites.includes(:surfboard)
  end

  def create
    @surfboard = Surfboard.find(params[:surfboard_id])
    @favorite = current_user.favorites.new(surfboard: @surfboard)
    @favorite.surfboard = @surfboard
    if @favorite.save
      redirect_to surfboard_path(@surfboard), notice: 'Surfboard added to favorites!'
    else
      redirect_to surfboard_path(@surfboard), alert: 'Unable to add surfboard to favorites.'
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to favorites_path, notice: 'Surfboard removed from favorites.'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: :index

  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @surfboard = Surfboard.find(params[:surfboard_id])
    @review = Review.new(review_params)
    @review.surfboard = @surfboard
    if @review.save
      redirect_to surfboard_path(@surfboard)
    else
      render 'surfboard/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/surfboards_controller.rb
class SurfboardsController < ApplicationController
  before_action :set_surfboard, only: [:destroy]
  def index
    @surfboards = Surfboard.all
    @markers = @surfboards.geocoded.map do |surfboard|
      {
        lat: surfboard.latitude,
        lng: surfboard.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {surfboard: surfboard})
      }
    end
  end

  def show
    if !current_user
      redirect_to new_user_registration_path
      return
    end
    @surfboard = Surfboard.find(params[:id])
    @review = Review.new
    @favorite = current_user.favorites.new
    @surfboards = Surfboard.all
    @markers = @surfboards.geocoded.map do |surfboard|
      {
        lat: surfboard.latitude,
        lng: surfboard.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {surfboard: surfboard})
      }
    end
  end

  def edit
  end

  def create
    @surfboard = Surfboard.new(surfboard_params)
    # @surfboard.booking = @booking
    @surfboard.user = current_user
    if @surfboard.save!
      redirect_to surfboards_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @surfboard = Surfboard.new
  end

  def update
  end

  def destroy
    @surfboard.destroy
    redirect_to surfboards_path, status: :see_other
  end

  private
  def surfboard_params
    params.require(:surfboard).permit(:name, :description, :color, :size, :price, :photo, :address)
  end
  def set_surfboard
    @surfboard = Surfboard.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Delete Booking</h1>
<%= link_to "Delete",
  booking_path(@booking),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/bookings/index.html.erb
<div class="container mt-3">
  <h1 class="text-center mb-4">Dashboard</h1>

  <div class="mb-5">
    <h2>View Your Bookings 🌊 🏄🏽‍♂️</h2>
    <div class="row">
      <% @bookings.each do |booking| %>
        <div class="col-md-2 col-sm-4 mb-4">
          <div class="card d-flex flex-column" style="height: 400px;">
            <%= link_to surfboard_path(booking.surfboard) do %>
              <% if booking.surfboard.photo.attached? %>
                <%= cl_image_tag booking.surfboard.photo.key, crop: :fill, class: "card-img-top", style: "height: 150px; width: 100%; object-fit: contain;" %>
              <% else %>
                <img class="card-img-top" src="<%= booking.surfboard.image_url %>" alt="<%= booking.surfboard.name %>" style="height: 150px; width: 100%; object-fit: contain;">
              <% end %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= booking.surfboard.name %></h5>
              <p><strong>Price:</strong> $<%= booking.surfboard.price %></p>
              <p><strong>Color:</strong> <%= booking.surfboard.color %></p>
              <p><strong>Size:</strong> <%= booking.surfboard.size %></p>
              <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-surfboard" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>


  <div class="mb-5">
    <h2>View Booking Requests for Your Surfboards 🌊 🏄🏽‍♂️</h2>
    <div class="row">
      <% @surfboards.each do |surfboard| %>
        <% if surfboard.user == current_user %>
          <% booking_requests = @booking_requests.select { |br| br.surfboard == surfboard } %>

          <% if booking_requests.any? %>
            <% booking_requests.each do |booking_request| %>
              <div class="col-md-6 col-lg-4 mb-4">
                <div class="card d-flex flex-row" style="height: auto;">
                  <div class="card-img-left" style="width: 200px; height: 200px; overflow: hidden;">
                    <%= link_to surfboard_path(booking_request.surfboard) do %>
                      <% if booking_request.surfboard.photo.attached? %>
                        <%= cl_image_tag booking_request.surfboard.photo.key, crop: :fill, class: "card-img-top", style: "height: 100%; width: 100%; object-fit: cover;" %>
                      <% else %>
                        <img class="card-img-top" src="<%= booking_request.surfboard.image_url %>" alt="<%= booking_request.surfboard.name %>" style="height: 100%; width: 100%; object-fit: cover;">
                      <% end %>
                    <% end %>
                  </div>

                  <div class="card-body d-flex flex-column justify-content-between" style="width: 100%; padding-right: 10px;">
                    <h5 class="card-title text-center"><%= booking_request.surfboard.name %></h5>
                    <p><strong>Price:</strong> $<%= booking_request.surfboard.price %></p>
                    <p><strong>Booking Date:</strong> <%= booking_request.created_at.strftime("%d %B %Y") %></p>
                    <p><strong>Start Time:</strong> <%= booking_request.start_time.strftime("%d %B %Y %H:%M") %></p>
                    <p><strong>End Time:</strong> <%= booking_request.end_time.strftime("%d %B %Y %H:%M") %></p>

                    <div class="d-flex justify-content-between align-items-center mt-3">
                      <% if booking_request.status == 'confirmed' %>
                        <button class="btn btn-success" disabled>Accepted</button>
                      <% else %>
                        <%= link_to accept_booking_path(booking_request), data: { turbo_method: :put, turbo_confirm: "Are you sure you want to accept this booking?" }, class: "btn-surfboard ml-auto" do %>
                          Accept
                        <% end %>

                        <%= link_to booking_path(booking_request), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel this booking?" }, class: "btn-surfboard" do %>
                          Cancel
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <p class="text-center w-100">No booking requests for this surfboard.</p>
          <% end %>
        <% end %> <!-- End: Check if current_user is the owner of the surfboard -->
      <% end %>
    </div>
  </div>







  <div class="mb-5">
    <h2>View Your Surfboards 🌊 🏄🏽‍♂️</h2>
    <div class="row">
      <% @surfboards.where(user_id: current_user.id).each do |surfboard| %>
        <div class="col-md-2 col-sm-4 mb-4">
          <div class="card d-flex flex-column" style="height: 350px;">
            <%= link_to surfboard_path(surfboard) do %>
              <% if surfboard.photo.attached? %>
                <%= cl_image_tag surfboard.photo.key, crop: :fill, class: "card-img-top", style: "height: 150px; width: 100%; object-fit: contain;" %>
              <% else %>
                <img class="card-img-top" src="<%= surfboard.image_url %>" alt="<%= surfboard.name %>" style="height: 150px; width: 100%; object-fit: contain;">
              <% end %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= surfboard.name %></h5>
              <p><strong>Price:</strong> $<%= surfboard.price %></p>
              <p><strong>Color:</strong> <%= surfboard.color %></p>
              <p><strong>Size:</strong> <%= surfboard.size %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <h1>Create a new booking for surfboard</h1>
  <p>Surf in style 🏄🏾</p>
  <%= simple_form_for [@surfboard, @booking] do |f| %>
    <%= f.label :start_time, "Start Time" %>
    <%= f.datetime_select :start_time %>
    <br>
    <br>
    <%= f.label :end_time, "End Time" %>
    <%= f.datetime_select :end_time %>
    <br>
    <br>

    <%= f.submit "Create Booking", class: "btn-surfboard" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class="card mb-3" style="max-width: 18rem;">
    <div class="card-body">
      <h5 class="card-title text-center">Congratulations! You have booked <%= @booking.surfboard.name %></h5>
      <% if @booking.surfboard.photo.attached? %>
        <div class="text-center">
          <%= cl_image_tag @booking.surfboard.photo.key, class: "img-fluid rounded", style: "width: 300px; height: 400px; object-fit: contain;" %>
        </div>
      <% else %>
        <div class="text-center">
          <img src="<%= @booking.surfboard.image_url %>" alt="<%= @booking.surfboard.name %> image" class="img-fluid rounded" style="width: 300px; height: 400px; object-fit: contain;">
        </div>
      <% end %>

      <p class="card-text"><strong>Price:</strong> $<%= @booking.surfboard.price %></p>
      <p class="card-text"><strong>Color:</strong> <%= @booking.surfboard.color %></p>
      <p class="card-text"><strong>Size:</strong> <%= @booking.surfboard.size %></p>
      <div class="d-flex justify-content-between align-items-center">
        <%= link_to booking_path(@booking),
                    data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                    class: "btn-surfboard btn-sm" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
        <%= link_to "See All Your Bookings", bookings_path, class: "btn-surfboard btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="container mt-5">
  <div class="header">
    <h1>My Favourites</h1>
  </div>
  <div class="row">
    <% @favorites.each do |favorite| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="height: 100%; display: flex; flex-direction: column;">
          <% if favorite.surfboard.photo.attached? %>
            <%= cl_image_tag favorite.surfboard.photo.key, class: "card-img-top", style: "width: 100%; height: 200px; object-fit: contain;" %>
          <% else %>
            <img src="<%= favorite.surfboard.image_url %>" alt="<%= favorite.surfboard.name %>" class="card-img-top" style="width: 100%; height: 200px; object-fit: contain;">
          <% end %>
          <div class="card-body d-flex flex-column" style="flex-grow: 1;">
            <h5 class="card-title"><%= favorite.surfboard.name %></h5>
            <p><strong>Price:</strong> $<%= favorite.surfboard.price %></p>
            <p><strong>Size:</strong> <%= favorite.surfboard.size %></p>
            <%= link_to favorite_path(favorite), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this from your favorites?" }, class: "btn btn-warning btn-sm mt-auto" do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurfEasy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Felipa&family=Imperial+Script&family=Yuji+Mai&display=swap" rel="stylesheet">

  </head>

  <body class="d-flex flex-column min-vh-100">
    <header>
      <%= render "shared/navbar" %>
    </header>

    <main class="flex-grow-1">
    <%= yield %>
    <%= render "shared/flashes" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </main>

    <footer>
      <%= render "shared/footer", year: Time.current.year %>
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
<div class="landing-page">
  <div class="content">
    <h1>Welcome to SurfEasy</h1>
    <p>Discover the ultimate surfing experience with our innovative surfboards.</p>
    <%= link_to "ENTER SURFBOARD EXPERIENCE NOW", surfboards_path , class: "btn-surfboard" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class=" footer">
  <p class="mb-0">&copy; <%= year %> SurfEasy. All Rights Reserved.</p>
  <div>
    <a href="#" class="me-3">About Us</a>
    <a href="#" class="me-3">Contact Us</a>
    <a href="#">Privacy Policy</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo_surf.png", alt: "Logo", style: "height: 70px;" %>
      <% end %>
      <%= link_to "SurfEasy", root_path, class: "nav-link"%>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to surfboards_path, class: "nav-link" do %>
            <i class="fa-solid fa-house"></i>
            <% end  %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a new Surfboard", new_surfboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.pic_url.present? %>
                <%= image_tag current_user.pic_url, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4YreOWfDX3kK-QLAbAL4ufCPc84ol2MA8Xg&s", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "My Favourites", favorites_path, class: "dropdown-item" %>
              <%= link_to "My Dashboard", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to surfboards_path, class: "nav-link" do %>
            <i class="fa-solid fa-house"></i>
            <% end  %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/surfboards/_info_window.html.erb
<h2><%= surfboard.name %></h2>
<p><%= surfboard.address %></p>

app/views/surfboards/create.html.erb
<h1>Surfboards#create</h1>
<p>Find me in app/views/surfboards/create.html.erb</p>

app/views/surfboards/destroy.html.erb
<h1>Surfboards#destroy</h1>
<%= link_to "Delete",
  surfboard_path(@surfboard),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<p>Find me in app/views/surfboards/destroy.html.erb</p>

app/views/surfboards/edit.html.erb
<h1>Surfboards#edit</h1>
<p>Find me in app/views/surfboards/edit.html.erb</p>

app/views/surfboards/index.html.erb
<div class="container">
<div class="header">
  <h1>Check Out These Amazing Surfboards!</h1>
  <h2>Surf in style 🏄🏾</h2>
</div>
  <div class="cards">
    <% @surfboards.each do |surfboard| %>
      <div class="card-product">
      <% if surfboard.photo.attached? %>
        <%= cl_image_tag surfboard.photo.key, crop: :fill %>
      <% else %>
        <img src="<%= surfboard.image_url %>" alt="<%= surfboard.name %> image" width="200">
      <% end %>
        <div class="card-product-infos">
          <%= link_to surfboard_path(surfboard), class: "card-link" do %>
            <h3><%= surfboard.name %></h3>
            <p>Size: <%= surfboard.size %></p>
            <p>Price: £<%= surfboard.price %>/day</p>
            <p>Description: <%= surfboard.description %></p>
          <% end %>
        </div>

      </div>
    <% end %>
  </div>
  <br>
  <br>
  <div class="text-center">
    <h2>Locations of our Surfboards</h2>
    <div class="mt-4" style="width: 100%; height: 300px;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/surfboards/new.html.erb
<div class="container">
  <h1>Add your very own Surfboard</h1>
  <%= simple_form_for(@surfboard) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :color %>
    <%= f.input :size %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Create Surfboard", class: "btn-surfboard" %>
  <% end %>
<div>

app/views/surfboards/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-4">
      <% if @surfboard.photo.attached? %>
        <%= cl_image_tag @surfboard.photo.key, class: "img-fluid rounded", style: "width: 300px; height: 400px; object-fit: cover;" %>
      <% else %>
        <img src="<%= @surfboard.image_url %>" alt="<%= @surfboard.name %> image" class="img-fluid rounded" style="width: 300px; height: 400px; object-fit: cover;">
      <% end %>
    </div>

    <div class="col-md-4">
      <div>
        <h1 class="mb-1"><%= @surfboard.name %></h1>
        <p><strong>Description:</strong> <%= @surfboard.description %></p>
        <p><strong>Price:</strong> $<%= @surfboard.price %>/day</p>
        <p><strong>Color:</strong> <%= @surfboard.color %></p>
        <p><strong>Size:</strong> <%= @surfboard.size %></p>
        <p><strong>Owner:</strong> <%= @surfboard.user.first_name %> <%= @surfboard.user.last_name %></p>
        <% if @surfboard.address.present? %>
          <p><strong>Address:</strong> <%= @surfboard.address %></p>
        <% end %>

        <div class="d-flex align-items-center mb-1">
          <%= link_to "Book this Surfboard", new_surfboard_booking_path(@surfboard), class: "btn-surfboard btn-lg" %>
        </div>

        <div class="d-flex align-items-center mb-1">
          <% if current_user.favorites.find_by(surfboard: @surfboard).nil? %>
            <%= simple_form_for [@surfboard, @favorite] do |f| %>
              <%= f.submit "⭐Add to Favorites", class: "btn-surfboard" %>
            <% end %>
          <% else %>
            <%= simple_form_for [@surfboard, @favorite] do |f| %>
              <%= f.submit "⭐ Added to Favorites", class: "btn-surfboard", disabled: true %>
            <% end %>
          <% end %>
        </div>

        <% if @surfboard.user == current_user %>
          <%= link_to surfboard_path(@surfboard), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-surfboard mt-2" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="mt-4" style="width: 100%; height: 300px;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-6">
      <h3>Reviews</h3>
      <% @surfboard.reviews.each do |review| %>
        <div class="review mb-3">
          <p><%= review.comment %></p>
          <p>Rating: <%= review.rating %><%= '⭐' * review.rating %></p>
        </div>
      <% end %>
    </div>

    <div class="col-md-6">
      <h3>Add a new Review</h3>
      <%= simple_form_for [@surfboard, @review] do |f| %>
        <%= f.input :comment, label: "Review", input_html: { class: "form-control" } %>
        <%= f.input :rating, collection: 1..5, label: "Rating", input_html: { class: "form-control" } %>
        <%= f.submit "Submit Review", class: "btn-surfboard mt-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/surfboards/update.html.erb
<h1>Surfboards#update</h1>
<p>Find me in app/views/surfboards/update.html.erb</p>